### ISSUE TITLE
Set temperature on manual mode

### ISSUE THREAD

**Issue by larsnet** [ChrisTerBeke/homey-remeha#6]
Hi,

First thank you for this app!
I use my Etwist on manual mode with no schedule active.
When i change the temperature in Homey, i see in the Remeha Home app there is a temperature timer active.
Also the thermostat switch to a Heating schedule.
Is it possible to change the request to "/climate-zones/{climate_zone_id}/modes/manual"?
See: https://github.com/msvisser/remeha_home/blob/main/documentation/api.md#post-climate-zonesclimate_zone_idmodesmanual
Or maybe set a option to choose if you want a temporary override or manual adjustment (without activating a schedule)?

**Comment by ChrisTerBeke** [comment]
I propose the following behavior: when you're overriding the temperature and currently a schedule is active, it will fall back to the schedule after some time (current behavior), but if no schedule is currently active, it'll say in manual mode on the configured temperature. I think this is the only way to do this within the constraints of the Homey thermostat UI (I cannot add additional options to the UI where you set the temperature).
